name: "Ollama"

on:
  pull_request:
    branches: [master]

jobs:
  analyze:
    name: Ollama review test
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 0  # Fetch full history to allow diffing

    - name: Install Ollama
      run: |
        curl -fsSL https://ollama.com/install.sh | bash
        sudo systemctl enable ollama
        sudo systemctl start ollama
        ollama pull qwen2.5-coder:3b
      shell: bash

    - name: Get full PR diff
      run: |
        # Fetch the latest changes from master
        git fetch origin master
        
        # Get the full diff of the PR
        full_diff=$(git diff origin/master)

        # Skip if there are no changes
        if [[ -z "$full_diff" ]]; then
          echo "No changes detected. Skipping review."
          exit 0
        fi

        # Escape the diff for JSON
        full_diff_escaped=$(echo "$full_diff" | jq -Rs .)

        # Create the payload for Ollama
        payload=$(jq -n --arg model "qwen2.5-coder:3b" --arg prompt "Review the following git diff for the entire PR. Check for potential security issues, bugs, typos, and possible improvements. Provide your response in plain text format (no Markdown or code formatting):

\`\`\`
$full_diff_escaped
\`\`\`" '{
          model: $model,
          prompt: $prompt,
          stream: false
        }')

        # Debug: Print the payload being sent
        echo "Payload: $payload"

        # Make the request to Ollama
        response=$(curl -s http://127.0.0.1:11434/api/generate -d "$payload")

        # Debug: Print the raw response from Ollama
        echo "Raw response: $response"

        # Extract the review from the response
        review=$(echo "$response" | jq -r '.response')

        # Debug: Print the extracted review
        echo "Extracted review: $review"

        # Skip if no review was generated
        if [[ -z "$review" ]]; then
          echo "No review generated. Skipping comment."
          exit 0
        fi

        # Post the review as a comment on the pull request
        gh pr comment ${{ github.event.pull_request.number }} --body "$review"
      shell: bash