name: "Ollama"

on:
  push:
    branches: [master]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [master]


jobs:
  analyze:
    name: Ollama review test
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        # We must fetch at least the immediate parents so that if this is
        # a pull request then we can checkout the head.
        fetch-depth: 0

    - name: Install Ollama
      run: |
        curl -fsSL https://ollama.com/install.sh | bash
        sudo systemctl enable ollama
        sudo systemctl start ollama
        ollama pull codegemma
      shell: bash

    - name: Get modified files
      id: get-modified-files
      uses: tj-actions/changed-files@v45

    - name: Review modified files
      env:
        GITHUB_TOKEN: ${{ github.token }}
      run: |

        for file in ${{ steps.get-modified-files.outputs.all_changed_files }}; do
          # Read the file content and escape it for JSON
          file_content=$(cat "$file" | jq -Rs .)
          
          # Send the file content to Ollama for review
          modified_file_review=$(curl -s http://127.0.0.1:11434/api/generate -d '{
            "model": "codegemma",
            "prompt": "Review the following file:\n\n```\n'"$file_content"'\n```",
            "stream": false
          }' | jq -r '.response')
          
          # Format the review comment
          file_comment="Ollama Code Review for \`$file\`:\n\n$modified_file_review"
          
          # Append the review to the output file
          echo "$file_comment" >> ollama_review.txt
        done

        gh pr comment ${{ github.event.pull_request.number }} --body "$(cat ollama_review.txt)"
      shell: bash
